-- SQL Schema for MuskiGuess Game (PostgreSQL 16)
-- Defines tables for user accounts and gameplay statistics, following snake_case naming and best practices.

-- ==================================================
-- Table: users - stores user account details
-- ==================================================
CREATE TABLE users (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    username VARCHAR(12) NOT NULL,              -- User's nickname (1-12 alphanumeric characters, no spaces or special chars)
    email VARCHAR(255) NOT NULL UNIQUE,         -- User's email address (must be unique)
    password_hash TEXT NOT NULL,               -- Hashed password for authentication
    reset_token VARCHAR(6),                    -- Optional 6-character token for password reset
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,  -- Account creation timestamp (defaults to now)
    CONSTRAINT chk_username_valid CHECK (username ~ '^[A-Za-z0-9]+$'),  -- Username must be only letters and numbers (no special characters or spaces)
    CONSTRAINT chk_reset_token_length CHECK (
        reset_token IS NULL OR reset_token ~ '^[A-Za-z0-9]{6}$'
    )  -- If reset_token is provided, it must be exactly 6 alphanumeric characters
);

-- Add descriptive comments to the users table and its columns for documentation
COMMENT ON TABLE users IS 'Stores registered user accounts for the MuskiGuess game.';
COMMENT ON COLUMN users.id IS 'Primary key: Unique user identifier.';
COMMENT ON COLUMN users.username IS 'User-chosen nickname (1-12 alphanumeric characters, no spaces/special characters).';
COMMENT ON COLUMN users.email IS 'User email address, used for login and communication (must be unique).';
COMMENT ON COLUMN users.password_hash IS 'Password hash for user authentication (e.g., bcrypt).';
COMMENT ON COLUMN users.reset_token IS 'Optional 6-character reset code for password recovery (null if not in use).';
COMMENT ON COLUMN users.created_at IS 'Timestamp when the account was created (automatically set to current time).';

-- ==================================================
-- Table: stats - tracks gameplay statistics per user per mode
-- ==================================================

-- First, create an enum type for game modes (to ensure only valid modes are used)
CREATE TYPE game_mode AS ENUM ('classic', 'dupleto', 'quapleto', 'multiplayer', 'total');

CREATE TABLE stats (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    user_id INTEGER NOT NULL,                        -- Reference to the user this stats record belongs to
    mode game_mode NOT NULL,                         -- Game mode for this stats record (classic, dupleto, quapleto, multiplayer, or total)
    num_games INTEGER NOT NULL DEFAULT 0,            -- Total number of games played in this mode by the user
    num_wins INTEGER NOT NULL DEFAULT 0,             -- Number of games won in this mode by the user
    num_losses INTEGER GENERATED ALWAYS AS (num_games - num_wins) STORED,  -- Number of games lost (computed as num_games minus num_wins)
    num_multiplayer_games INTEGER,                   -- (For mode='multiplayer' only) Number of multiplayer sessions played
    num_multiplayer_wins INTEGER,                    -- (For mode='multiplayer' only) Number of multiplayer sessions won
    num_multiplayer_losses INTEGER GENERATED ALWAYS AS (num_multiplayer_games - num_multiplayer_wins) STORED,  -- (For mode='multiplayer') Losses in multiplayer (computed)
    CONSTRAINT fk_stats_user FOREIGN KEY (user_id) 
        REFERENCES users(id) ON DELETE CASCADE,      -- Foreign key: link to users table, cascade delete to remove stats if user is deleted
    CONSTRAINT uq_stats_user_mode UNIQUE (user_id, mode),  -- Ensure one stats record per user per mode (no duplicates)
    CONSTRAINT chk_wins_not_exceed_games CHECK (num_wins <= num_games),  -- Wins cannot exceed total games
    CONSTRAINT chk_multiplayer_fields CHECK (
        -- If mode is 'multiplayer', the multiplayer fields must be not null (filled);
        -- If mode is not 'multiplayer', those fields should remain null (not applicable).
        (mode = 'multiplayer' AND num_multiplayer_games IS NOT NULL AND num_multiplayer_wins IS NOT NULL)
        OR (mode <> 'multiplayer' AND num_multiplayer_games IS NULL AND num_multiplayer_wins IS NULL)
    )
);

-- Add descriptive comments to the stats table and its columns
COMMENT ON TABLE stats IS 'Stores per-user statistics for each game mode (including a total across all modes).';
COMMENT ON COLUMN stats.id IS 'Primary key: Unique identifier for this stats record.';
COMMENT ON COLUMN stats.user_id IS 'Foreign key to users.id, identifying which user these stats belong to.';
COMMENT ON COLUMN stats.mode IS 'Game mode for this statistics record (one of: classic, dupleto, quapleto, multiplayer, total).';
COMMENT ON COLUMN stats.num_games IS 'Total number of games played by the user in this mode.';
COMMENT ON COLUMN stats.num_wins IS 'Total number of games won by the user in this mode.';
COMMENT ON COLUMN stats.num_losses IS 'Total number of games lost in this mode (computed as num_games minus num_wins).';
COMMENT ON COLUMN stats.num_multiplayer_games IS 'Number of multiplayer game sessions played by the user (only applicable if mode = multiplayer).';
COMMENT ON COLUMN stats.num_multiplayer_wins IS 'Number of multiplayer game sessions won by the user (only applicable if mode = multiplayer).';
COMMENT ON COLUMN stats.num_multiplayer_losses IS 'Number of multiplayer game sessions lost (computed as num_multiplayer_games minus num_multiplayer_wins).';