import random

words = [
    "abaco", "bosta", "monte", "monge", "abate",
    "acima", "acido", "lacre", "porra", "afeto",
    "agora", "ajuda", "marca", "jatos", "aluno",
    "amigo", "anexo", "mijar", "apelo", "nicho",
    "aroma", "atual", "aviao", "banco", "visto",
    "bingo", "bolha", "telha", "bravo", "cacau",
    "raios", "canto", "carro", "casal", "certa",
    "cesto", "cinta", "claro", "cobre", "corte",
    "costa", "cravo", "dente", "dolar", "doido",
    "ducha", "jegue", "festa", "firme", "lindo",
    "gente", "gordo", "grito", "forca", "gelar",
    "hotel", "jogos", "jovem", "lagoa", "kiwis",
    "manga", "manto", "massa", "misto", "moeda",
    "mundo", "norte", "notas", "piano", "pinta",
    "plano", "ponto", "homem", "quero", "rango",
    "sabor", "santo", "sorte", "tampa", "tempo",
    "tigre", "tinta", "torta", "trigo", "vazio",
    "legal", "menta", "local", "trena", "honra",
    "afora", "agudo", "ainda", "areia", "axila",
    "barco", "baixo", "banho", "bazar", "bomba",
    "barro", "busto", "burro", "bossa", "breve",
    "brisa", "cabra", "carga", "clima", "cifra",
    "cerne", "ciclo", "coral", "corpo", "couro",
    "curto", "dorso", "deusa", "dengo", "dardo",
    "dueto", "exato", "exame", "folha", "fruta",
    "fenda", "fugar", "fugir", "fazer", "beber",
    "abrir", "andar", "comer", "dizer", "falar",
    "lutar", "viver", "estar", "gasto", "gabar",
    "galho", "gesto", "girar", "humor", "horto",
    "idoso", "idade", "irado", "itens", "jeito",
    "junco", "joias", "kilos", "carma", "livro",
    "lugar", "lento", "largo", "luzes", "moral",
    "morte", "media", "minha", "molho", "metro",
    "mimar", "navio", "noite", "natal", "nobre",
    "ninja", "otimo", "opaco", "outro", "pegar",
    "pular", "prato", "preto", "penca", "quase",
    "raiva", "risco", "rural", "remar", "repor",
    "ramal", "sinal", "salto", "senso", "sobra",
    "suave", "samba", "tarde", "tocha", "tarja",
    "trono", "vento", "tocar", "usado", "unido",
    "urgir", "vagar", "velho", "veloz", "viver",
    "xisto", "zebra", "zarpa", "zumbo", "zanga",
    "otima", "pardo", "rolar", "temer", "mimar"
]
# Lista EN fácil (5 letras, vocabulário simples)
english_words_easy = [
    "apple", "trade", "chair", "house", "water",
    "blaze", "doors", "happy", "green", "smile",
    "light", "trial", "tiger", "pizza", "beach",
    "cloud", "dance", "drink", "fruit", "games",
    "birch", "troop", "stone", "heart", "above",
    "blind", "stars", "sleep", "dream", "money",
    "blink", "smell", "clean", "sweet", "angel",
    "watch", "story", "snake", "truck", "bunny",
    "clear", "shirt", "pants", "shoes", "brown",
    "black", "white", "lemon", "honey", "chess",
    "climb", "pearl", "bread", "flame", "candy",
    "minor", "drain", "rainy", "storm", "adapt",
    "field", "grass", "river", "table", "below",
    "couch", "phone", "mouse", "towel", "clock",
    "plant", "piano", "teeth", "socks", "skirt",
    "movie", "block", "learn", "paint", "skies",
    "title", "think", "stand", "laugh", "touch",
    "today", "spoon", "plate", "quest", "slash",
    "brush", "music", "arise", "flour", "start",
    "torch", "zebra", "eagle", "sheep", "goose",
    "horse", "kitty", "puppy", "queue", "slimy",
    "grape", "peach", "sneak", "berry", "melon",
    "onion", "toast", "sugar", "juice", "cream",
    "paper", "books", "penal", "queen", "under",
    "toxic", "motel", "angry", "tired", "quiet",
    "ready", "sunny", "recap", "proof", "windy",
    "north", "south", "rogue", "gross", "waste",
    "ocean", "world", "earth", "space", "witch"
]


def get_random_word(lang: str = 'pt'):
    if (lang or '').lower() == 'en':
        return random.choice(english_words_easy)
    return random.choice(words)