import random

words = [
    "abaco", "bosta", "monte", "monge", "abate",
    "acima", "acido", "lacre", "porco", "afeto",
    "agora", "ajuda", "marca", "jatos", "aluno",
    "amigo", "anexo", "mijar", "apelo", "nicho",
    "aroma", "atual", "aviao", "banco", "visto",
    "bingo", "bolha", "telha", "bravo", "cacau",
    "raios", "canto", "carro", "casal", "certa",
    "cesto", "cinta", "claro", "cobre", "corte",
    "costa", "cravo", "dente", "dolar", "doido",
    "ducha", "jegue", "festa", "firme", "lindo",
    "gente", "gordo", "grito", "forca", "gelar",
    "hotel", "jogos", "jovem", "lagoa", "kiwis",
    "manga", "manto", "massa", "misto", "moeda",
    "mundo", "norte", "notas", "piano", "pinta",
    "plano", "ponto", "homem", "quero", "rango",
    "sabor", "santo", "sorte", "tampa", "tempo",
    "tigre", "tinta", "torta", "trigo", "vazio",
    "legal", "menta", "local", "trena", "honra",
    "afora", "agudo", "ainda", "areia", "axila",
    "barco", "baixo", "banho", "bazar", "bomba",
    "barro", "busto", "burro", "bossa", "breve",
    "brisa", "cabra", "carga", "clima", "cifra",
    "cerne", "ciclo", "coral", "corpo", "couro",
    "curto", "dorso", "deusa", "dengo", "dardo",
    "dueto", "exato", "exame", "folha", "fruta",
    "fenda", "fugar", "fugir", "fazer", "beber",
    "abrir", "andar", "comer", "dizer", "falar",
    "lutar", "viver", "estar", "gasto", "gabar",
    "galho", "gesto", "girar", "humor", "horto",
    "idoso", "idade", "irado", "itens", "jeito",
    "junco", "joias", "kilos", "carma", "livro",
    "lugar", "lento", "largo", "luzes", "moral",
    "morte", "media", "minha", "molho", "metro",
    "mimar", "navio", "noite", "natal", "nobre",
    "ninja", "otimo", "opaco", "outro", "pegar",
    "pular", "prato", "preto", "penca", "quase",
    "raiva", "risco", "rural", "remar", "repor",
    "ramal", "sinal", "salto", "senso", "sobra",
    "suave", "samba", "tarde", "tocha", "tarja",
    "trono", "vento", "tocar", "usado", "unido",
    "urgir", "vagar", "velho", "veloz", "viver",
    "cenho", "zebra", "zarpa", "zumba", "junta",
    "otima", "pardo", "rolar", "temer", "mimar",
    # Palavras adicionadas (5 letras, sem acento; verbos no infinitivo quando aplicável)
    "sagaz", "limpo", "termo", "negro", "exito", "mexer", "etica", "algoz", "plena", "tenue",
    "mutua", "sobre", "aquem", "visar", "poder", "vigor", "sutil", "porem", "ideia", "sanar",
    "audaz", "inato", "desde", "muito", "justo", "sonho", "torpe", "razao", "icone", "egide",
    "etnia", "futil", "haver", "lapso", "entao", "expor", "bocal", "seara", "habil", "saber",
    "mutuo", "graca", "xibiu", "obice", "avido", "ardil", "pesar", "dever", "causa", "tenaz",
    "brado", "paria", "crivo", "temor", "coser", "genro", "comum", "apice", "posse", "prole",
    "animo", "assaz", "ceder", "corja", "pauta", "fugaz", "ansia", "culto", "atroz", "digno",
    "vulgo", "vicio", "gleba", "saude", "criar", "cozer", "todos", "reves", "pudor", "dogma",
    "denso", "nenem", "louco", "atras", "regra", "ordem", "limbo", "pedir", "clava", "feliz",
    "impor", "usura", "banal", "juizo", "levar", "olhar", "tomar", "visao", "genio", "ouvir"
]
# Lista EN fácil (5 letras, vocabulário simples)
english_words_easy = [
    "apple", "trade", "chair", "house", "water",
    "blaze", "doors", "happy", "green", "smile",
    "light", "trial", "tiger", "pizza", "beach",
    "cloud", "dance", "drink", "fruit", "games",
    "birch", "troop", "stone", "heart", "above",
    "blind", "stars", "sleep", "dream", "money",
    "blink", "smell", "clean", "sweet", "angel",
    "watch", "story", "snake", "truck", "bunny",
    "clear", "shirt", "pants", "shoes", "brown",
    "black", "white", "lemon", "honey", "chess",
    "climb", "pearl", "bread", "flame", "candy",
    "minor", "drain", "rainy", "storm", "adapt",
    "field", "grass", "river", "table", "below",
    "couch", "phone", "mouse", "towel", "clock",
    "plant", "piano", "teeth", "socks", "skirt",
    "movie", "block", "learn", "paint", "skies",
    "title", "think", "stand", "laugh", "touch",
    "today", "spoon", "plate", "quest", "slash",
    "brush", "music", "arise", "flour", "start",
    "torch", "zebra", "eagle", "sheep", "goose",
    "horse", "kitty", "puppy", "queue", "slimy",
    "grape", "peach", "sneak", "berry", "melon",
    "onion", "toast", "sugar", "juice", "cream",
    "paper", "books", "penal", "queen", "under",
    "toxic", "motel", "angry", "tired", "quiet",
    "ready", "sunny", "recap", "proof", "windy",
    "north", "south", "rogue", "gross", "waste",
    "ocean", "world", "earth", "space", "witch",
    # Added 100 new English words (5 letters, base form if verb)
    "hello", "peace", "magic", "brain", "video", "check", "words", "lines", "piece", "shape",
    "share", "thing", "sound", "logic", "quick", "break", "crack", "place", "write", "speak",
    "beard", "chase", "cross", "taste", "flare", "split", "study", "brave", "loose", "tight",
    "grace", "grind", "spice", "cider", "cabin", "camel", "cater", "crown", "draft", "final",
    "focus", "force", "front", "giant", "glove", "grain", "group", "guide", "guest", "human",
    "image", "judge", "month", "never", "night", "noise", "point", "press", "raise", "reach",
    "reply", "score", "serve", "short", "small", "stage", "teach", "thank", "total", "truth",
    "value", "voice", "whole", "young", "after", "other", "which", "their", "there", "first",
    "would", "these", "click", "price", "state", "email", "items", "hotel", "store", "terms",
    "right", "local", "forum", "based", "index", "being", "women", "pages", "found", "photo"
]


def get_random_word(lang: str = 'pt'):
    if (lang or '').lower() == 'en':
        return random.choice(english_words_easy)
    return random.choice(words)
