import random

words = [
    "abaco", "bosta", "monte", "monge", "abate", "acima", "acido", "lacre", "porco", "afeto",
    "agora", "ajuda", "marca", "jatos", "aluno", "amigo", "anexo", "mijar", "apelo", "nicho",
    "aroma", "atual", "aviao", "banco", "visto", "bingo", "bolha", "telha", "bravo", "cacau",
    "raios", "canto", "carro", "casal", "certa", "cesto", "cinta", "claro", "cobre", "corte",
    "costa", "cravo", "dente", "dolar", "doido", "ducha", "jegue", "festa", "firme", "lindo",
    "gente", "gordo", "grito", "forca", "gelar", "hotel", "jogos", "jovem", "lagoa", "kiwis",
    "manga", "manto", "massa", "misto", "moeda", "mundo", "norte", "notas", "piano", "pinta",
    "plano", "ponto", "homem", "quero", "rango", "sabor", "santo", "sorte", "tampa", "tempo",
    "tigre", "tinta", "torta", "trigo", "vazio", "legal", "menta", "local", "trena", "honra",
    "afora", "agudo", "ainda", "areia", "axila", "barco", "baixo", "banho", "bazar", "bomba",
    "barro", "busto", "burro", "bossa", "breve", "brisa", "cabra", "carga", "clima", "cifra",
    "cerne", "ciclo", "coral", "corpo", "couro", "curto", "dorso", "deusa", "dengo", "dardo",
    "dueto", "exato", "exame", "folha", "fruta", "fenda", "fugar", "fugir", "fazer", "beber",
    "abrir", "andar", "comer", "dizer", "falar", "lutar", "viver", "estar", "gasto", "gabar",
    "galho", "gesto", "girar", "humor", "horto", "idoso", "idade", "irado", "itens", "jeito",
    "junco", "joias", "kilos", "carma", "livro", "lugar", "lento", "largo", "luzes", "moral",
    "morte", "media", "minha", "molho", "metro", "ninar", "navio", "noite", "natal", "nobre",
    "ninja", "otimo", "opaco", "outro", "pegar", "pular", "prato", "preto", "penca", "quase",
    "raiva", "risco", "rural", "remar", "repor", "ramal", "sinal", "salto", "senso", "sobra",
    "suave", "samba", "tarde", "tocha", "tarja", "trono", "vento", "tocar", "usado", "unido",
    "urgir", "vagar", "velho", "veloz", "pirar", "cenho", "zebra", "zarpa", "zumba", "junta",
    "otima", "pardo", "rolar", "temer", "mimar", "sagaz", "limpo", "termo", "negro", "exito",
    "mexer", "etica", "algoz", "plena", "tenue", "mutua", "sobre", "aquem", "visar", "poder",
    "vigor", "sutil", "porem", "ideia", "sanar", "audaz", "inato", "desde", "muito", "justo",
    "sonho", "torpe", "razao", "icone", "quilo", "etnia", "futil", "haver", "lapso", "entao",
    "expor", "bocal", "retro", "habil", "saber", "mutuo", "graca", "xibiu", "obice", "obito",
    "ardil", "pesar", "dever", "causa", "tenaz", "brado", "vetor", "crivo", "temor", "coser",
    "genro", "comum", "apice", "posse", "prole", "animo", "assar", "ceder", "volta", "pauta",
    "medos", "ansia", "culto", "atroz", "digno", "vulgo", "vicio", "gleba", "saude", "criar",
    "fonte", "todos", "reves", "pudor", "dogma", "denso", "nenem", "louco", "atras", "regra",
    "ordem", "limbo", "pedir", "clava", "feliz", "impor", "usura", "banal", "juizo", "levar",
    "olhar", "tomar", "visao", "genio", "ouvir", "caldo", "clara", "trair", "balde", "prova",
    "acaso", "adeus", "afiar", "amplo", "antes", "apito", "arcar", "ardor", "arroz", "astro",
    "balsa", "bater", "bicho", "bolar", "botar", "brava", "brejo", "bruto", "caber", "cacho",
    "caixa", "calar", "canal", "carne", "cerca", "cesta", "citar", "civil", "colar", "copia",
    "coxas", "cocar", "croca", "curar", "dados", "danar", "dedos", "dores", "drama", "densa",
    "errar", "etapa", "falha", "ferir", "feroz", "ferro", "ficar", "pinha", "arara", "fixar",
    "focar", "forno", "ganho", "garra", "golpe", "grato", "grave", "guiar", "haste", "horda",
    "imune", "laudo", "lavar", "leito", "ligar", "linha", "livre", "lixar", "lucro", "magro",
    "meigo", "meter", "mirar", "molar", "morar", "mover", "nasce", "nuvem", "odiar", "optar",
    "ornar", "outra", "parar", "passe", "peixe", "peido", "perna", "perto", "pinto", "pisar",
    "pleno", "podar", "puxar", "regar", "rente", "jejum", "rival", "rolha", "rosto", "roubo",
    "rufar", "ruido", "sacar", "salve", "selar", "sirva", "somar", "sonar", "sopra", "sopro",
    "sugar", "sumir", "talar", "tenso", "terno", "torso", "turma", "turvo", "janta", "valer",
    "vasto", "vazar", "vedar", "velar", "venda", "vivar", "vocal", "robos", "zelar", "zunir",
    "aguar", "algar", "alcar", "ameno", "amuar", "arduo", "arfar", "aviar", "azedo", "babar",
    "bafar", "balar", "banir", "bicar", "bocar", "bufar", "cavar", "cegar", "chato", "circo",
    "coado", "cozer", "cruel", "galos", "curva", "datar", "depor", "ditar", "dobar", "donos",
    "praga", "duros", "ecoar", "feder", "feiar", "fitar", "fluir", "furar", "gerar", "golar",
    "jarro", "rifar", "mamar", "manar", "manso", "matar", "mofar", "nadar", "nevoa", "notar",
    "picar", "pobre", "rosea", "rosar", "rouca", "sabio", "safar", "sopar", "tirar", "torar",
    "tosar", "verde", "motor", "amora", "ptose", "polar", "cagar", "mitos", "fitas", "mudar",
    "mudas", "aulas", "aviso", "azias", "bicos", "baila", "borda", "busca", "capuz", "calmo",
    "campo", "urina", "chave", "chuva", "cobra", "cofre", "couve", "danos", "droga", "durar",
    "eixos", "farol", "feira", "filho", "filha", "filme", "flora", "fauna", "finta", "fones",
    "fusao", "fugaz", "ganso", "giria", "morro", "grilo", "heroi", "hiato", "juros", "lanca",
    "latir", "lacos", "leigo", "lepra", "lesar", "licao", "medir", "meias", "melao", "micos",
    "obeso", "oncas", "oleos", "pacto", "padre", "papel", "pausa", "pelos", "peita", "pinga",
    "posar", "praca", "prima", "queda", "rasgo", "reter", "saldo", "senha", "surto", "tacar",
    "piada", "audio", "primo", "hifen", "harpa", "hindu", "junho", "julho", "juiza", "lasca"
    ]
# Lista EN fácil (5 letras, vocabulário simples)
english_words_easy = [
    "apple", "trade", "chair", "house", "water", "blaze", "doors", "happy", "green", "smile",
    "light", "trial", "tiger", "pizza", "beach", "cloud", "dance", "drink", "fruit", "games",
    "birch", "troop", "stone", "heart", "above", "blind", "stars", "sleep", "dream", "money",
    "blink", "smell", "clean", "sweet", "angel", "watch", "story", "snake", "truck", "bunny",
    "clear", "shirt", "pants", "shoes", "brown", "black", "white", "lemon", "honey", "chess",
    "climb", "pearl", "bread", "flame", "candy", "minor", "drain", "rainy", "storm", "adapt",
    "field", "grass", "river", "table", "below", "couch", "phone", "mouse", "towel", "clock",
    "plant", "piano", "teeth", "socks", "skirt", "movie", "block", "learn", "paint", "skies",
    "title", "think", "stand", "laugh", "touch", "today", "spoon", "plate", "quest", "slash",
    "brush", "music", "arise", "flour", "start", "torch", "zebra", "eagle", "sheep", "goose",
    "horse", "kitty", "puppy", "queue", "slimy", "grape", "peach", "sneak", "berry", "melon",
    "onion", "toast", "sugar", "juice", "cream", "paper", "books", "penal", "queen", "under",
    "toxic", "motel", "angry", "tired", "quiet", "ready", "sunny", "recap", "proof", "windy",
    "north", "south", "rogue", "gross", "waste", "ocean", "world", "earth", "space", "witch",
    "hello", "peace", "magic", "brain", "video", "check", "words", "lines", "piece", "shape",
    "share", "thing", "sound", "logic", "quick", "break", "crack", "place", "write", "speak",
    "beard", "chase", "cross", "taste", "flare", "split", "study", "brave", "loose", "tight",
    "grace", "grind", "spice", "cider", "cabin", "camel", "cater", "crown", "draft", "final",
    "focus", "force", "front", "giant", "glove", "grain", "group", "guide", "guest", "human",
    "image", "judge", "month", "never", "night", "noise", "point", "press", "raise", "reach",
    "reply", "score", "serve", "short", "small", "stage", "teach", "thank", "total", "truth",
    "value", "voice", "whole", "young", "after", "other", "which", "their", "there", "first",
    "would", "these", "click", "price", "state", "email", "items", "hotel", "store", "terms",
    "right", "local", "forum", "based", "index", "being", "women", "pages", "found", "photo",
    "agree", "alert", "align", "allow", "apron", "beast", "blend", "bliss", "bloom", "brisk",
    "charm", "claim", "clerk", "close", "craft", "crane", "crash", "creek", "crisp", "curve",
    "diner", "drive", "dwarf", "faith", "fancy", "flood", "frame", "frost", "ghost", "glass",
    "glory", "great", "hobby", "leads", "liver", "lodge", "lucky", "lunch", "mango", "meant",
    "mimic", "mount", "noble", "novel", "nurse", "oasis", "olive", "order", "party", "pilot",
    "pound", "quote", "rapid", "raven", "rider", "rough", "round", "route", "rugby", "rural",
    "saint", "scale", "shift", "shine", "shock", "smart", "smoke", "solar", "sport", "steel",
    "super", "sweat", "tough", "tower", "track", "train", "treat", "upper", "vapor", "vital",
    "vivid", "whale", "wheel", "whirl", "wings", "witty", "yield", "acorn", "admit", "adopt",
    "adore", "ahead", "alarm", "amber", "amend", "amuse", "anger", "apart", "arena", "argue",
    "ashes", "asset", "attic", "award", "bacon", "badge", "bagel", "baker", "baldy", "banjo",
    "basil", "basin", "batch", "beech", "beefy", "birth", "blast", "bleed", "blond", "blues",
    "board", "boost", "bound", "broad", "broom", "buddy", "buggy", "built", "bunch", "burns",
    "burst", "bushy", "buyer", "belly", "bench", "cable", "canal", "carve", "catch", "cease",
    "chili", "choir", "choke", "civic", "clash", "cling", "clown", "coach", "coast", "coral",
    "craze", "bingo", "drama", "creep", "crime", "cubic", "curse", "cycle", "daddy", "daily",
    "daisy", "dealt", "debut", "delay", "delta", "demon", "drawn", "dread", "dress", "drift",
    "drill", "drove", "dusty", "eager", "early", "elbow", "elite", "empty", "enjoy", "entry",
    "equal", "error", "event", "every", "armor", "array", "exact", "exist", "extra", "fable",
    "faint", "fairy", "false", "fatal", "favor", "feast", "fence", "fetch", "fiber", "fifth",
    "fifty", "fight", "arrow", "groan", "flock", "flora", "flush", "flute", "forth", "fresh",
    "funny", "given", "glare", "grant", "graph", "greed", "grill", "imply", "inner", "input",
    "guard", "guess", "habit", "handy", "harsh", "haste", "hatch", "haunt", "heavy", "hinge",
    "honor", "hover", "humor", "ideal", "irony", "issue", "jelly", "jolly", "karma", "kneel",
    "knife", "label", "labor", "large", "laser", "later", "layer", "leash", "level", "limit",
    "linen", "loyal", "lunar", "lyric", "maker", "maple", "march", "match", "mayor", "medal",
    "mercy", "metal", "might", "model", "moral", "mossy", "motor", "mover", "naked", "nerve",
    "newly", "ninth", "nylon", "offer", "opera", "orbit", "organ", "otter", "outer", "owner",
    "panda", "panel", "panic", "paste", "patch", "pause", "pedal", "penny", "perch", "phase",
    "pitch", "plain", "plead", "plush", "polar", "porch", "pride", "prime", "print", "prize",
    "probe", "proud", "punch", "radio", "ranch", "range", "realm", "rebel", "refer", "relax",
    "ridge", "risky", "rival", "robot", "ruler", "sable", "sauce", "scene", "scout", "screw",
    "sense", "shade", "shaft", "shake", "shame", "sharp", "shelf", "shoot", "shore", "shout",
    "silly", "skill", "slice", "slide", "slope", "snack", "solid", "spark", "spend", "spine",
    "spite", "spray", "squad", "stack", "stain", "stark", "steam", "stick", "stiff", "still",
    "stony", "strap", "straw", "strip", "stuck", "stuff", "swear", "swing", "sword", "tango",
    "tease", "theme", "thick", "third", "thorn", "those", "three", "threw", "throw", "token",
    "tonic", "topic", "trace", "trail", "trend", "tribe", "trick", "truly", "trunk", "tulip",
    "tuned", "twice", "uncle", "unite", "urban", "usage", "verse", "voter", "wagon", "weary",
    "weird", "wheat", "where", "while", "woman", "worry", "wound", "wreck", "wrong", "youth",
    "zones", "disco", "donor"
]


def get_random_word(lang: str = 'pt'):
    if (lang or '').lower() == 'en':
        return random.choice(english_words_easy)
    return random.choice(words)


def get_word_list(lang: str = 'pt'):
    if (lang or '').lower() == 'en':
        return english_words_easy
    return words
